#!/bin/bash

pdflatex Thesis.tex

if [[ "x$1" == "xref" ]]; then
    sed -i "s/_guideline_1994/guideline_1994/g" ThesisLibrary.bib
    makeindex Thesis.nlo -s nomencl.ist -o Thesis.nls
    bibtex Thesis.aux
    pdflatex Thesis.tex
    pdflatex Thesis.tex
fi

# gs -dSAFER -dBATCH -dNOPAUSE  -sDEVICE=pdfwrite -sOutputFile=output.pdf Thesis.pdf

